version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@date-io/moment"
    versions:
    - ">= 2.a, < 3"
  - dependency-name: aws-sdk
    versions:
    - 2.833.0
    - 2.834.0
    - 2.836.0
    - 2.837.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.872.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.877.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: "@rjsf/material-ui"
    versions:
    - 2.5.0
  - dependency-name: telegraf
    versions:
    - 4.0.2
    - 4.0.3
    - 4.1.0
    - 4.1.1
    - 4.1.2
    - 4.2.0
    - 4.2.1
  - dependency-name: serverless
    versions:
    - 2.25.1
    - 2.26.0
    - 2.27.1
  - dependency-name: google-auth-library
    versions:
    - 7.0.0
