version: '3'
services:
  workspace:
    # build: .
    image: hkssprangers/hkssprangers_devcontainer_workspace:20200808
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    environment:
      - TZ=Asia/Hong_Kong
      - MYSQL_ENDPOINT=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=devroot
    user: user
    command: sleep infinity
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=devroot
      - MYSQL_DATABASE=hkssprangers
    ports:
      - "3306:3306"
    volumes:
      - ../dev/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  node_modules:
