version: '3'
services:
  workspace:
    image: hkssprangers/hkssprangers_devcontainer_workspace:20211117141723
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    environment:
      - TZ=Asia/Hong_Kong
      - DEPLOY_STAGE=dev
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=devroot
    user: vscode
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    expose:
      - "80"
  mysql:
    image: mysql:8.0
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=devroot
      - MYSQL_DATABASE=hkssprangers
    expose:
      - "3306"
    volumes:
      - ../dev/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:2021.10.5
    environment:
      - TUNNEL_METRICS=cloudflared:44871
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    command: tunnel --no-autoupdate --url http://workspace:80
    expose:
      - "44871"
