version: '3'
services:
  workspace:
    image: ghcr.io/hkssprangers/hkssprangers_devcontainer:master
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    environment:
      - TZ=Asia/Hong_Kong
      - EARTHLY_BUILDKIT_HOST=tcp://earthly:8372
      - EARTHLY_REMOTE_CACHE=ghcr.io/hkssprangers/hkssprangers_cache:master
      - DEPLOY_STAGE=dev
      - COCKROACH_HOST=cockroachdb
      - COCKROACH_PORT=26257
      - COCKROACH_DATABASE=defaultdb
      - COCKROACH_USER=crdb
      - COCKROACH_PASSWORD=crdb
      - DATABASE_URL=postgresql://crdb:crdb@cockroachdb:26257/defaultdb?sslmode=disable
    user: vscode
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    expose:
      - "80"
  cockroachdb:
    # We use the unstable image here for easy config with env vars
    # https://github.com/cockroachdb/cockroach/commit/2862374a4743aece5707ea52d0ac17f6cb10dc7b
    image: cockroachdb/cockroach-unstable:v22.1.0-alpha.1
    environment:
      - TZ=UTC
      - COCKROACH_DATABASE=defaultdb
      - COCKROACH_USER=crdb
      - COCKROACH_PASSWORD=crdb
    expose:
      - "26257"
    command: start-single-node --insecure
    volumes:
      - ../dev/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared
    environment:
      - TUNNEL_METRICS=cloudflared:44871
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    command: tunnel --no-autoupdate --url http://workspace:80
    expose:
      - "44871"
  earthly:
    image: earthly/buildkitd:v0.6.30
    privileged: true
    environment:
      - BUILDKIT_TCP_TRANSPORT_ENABLED=true
    expose:
      - 8372
    volumes:
      # https://docs.earthly.dev/docs/guides/using-the-earthly-docker-images/buildkit-standalone#earthly_tmp_dir
      - earthly-tmp:/tmp/earthly:rw

volumes:
  earthly-tmp:
