version: '3'
services:
  workspace:
    # build: .
    image: hkssprangers/hkssprangers_devcontainer_workspace:20200808
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    environment:
      - HUB_HOST=selenium
    user: user
    command: sleep infinity

volumes:
  node_modules:
