name: CI
on: ["push", "pull_request"]

env:
  TZ: Asia/Hong_Kong
  EARTHLY_USE_INLINE_CACHE: "true"
  EARTHLY_SAVE_INLINE_CACHE: "true"
  EARTHLY_STRICT: "true"
  EARTHLY_PUSH: "${{ github.repository_owner == 'hkssprangers' && github.event_name == 'push' }}"
  FORCE_COLOR: 1

jobs:
  job:
    concurrency: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        if: success() && env.EARTHLY_PUSH == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.6/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Build devcontainer
        run: earthly +ci-images --GIT_REF_NAME="${{ github.ref_name }}" --GIT_SHA="${{ github.sha }}"
      - name: Build
        run: earthly +server
      - name: Build importGoogleForm
        run: earthly +importGoogleForm-js
      - name: Test
        run: earthly +test
      - name: Create .envrc
        if: success() && env.EARTHLY_PUSH == 'true'
        run: |
          cat > .envrc <<EOT
          export AWS_DEFAULT_REGION="ap-southeast-1"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          EOT
      - name: Pre-deploy check
        if: success() && env.EARTHLY_PUSH == 'true'
        run: earthly +pre-deploy-check
        env:
          EARTHLY_SECRET_FILES: .envrc=.envrc
      - name: Create .envrc
        if: success() && env.EARTHLY_PUSH == 'true'
        run: |
          cat > .envrc <<EOT
          export AWS_DEFAULT_REGION="ap-southeast-1"
          export AWS_ACCESS_KEY_ID="${{ secrets.SLS_AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}"
          export SERVERLESS_ACCESS_KEY="${{ secrets.SERVERLESS_ACCESS_KEY }}"
          export MYSQL_HOST="${{ secrets.MYSQL_HOST }}"
          export MYSQL_USER="${{ secrets.MYSQL_USER }}"
          export MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}"
          export FORM_READER_EMAIL="${{ secrets.FORM_READER_EMAIL }}"
          export FORM_READER_PRIVATE_KEY="${{ secrets.FORM_READER_PRIVATE_KEY }}"
          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
          export TWILIO_SID="${{ secrets.TWILIO_SID }}"
          export TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}"
          EOT
      - name: Deploy
        if: success() && env.EARTHLY_PUSH == 'true'
        run: earthly +deploy
        env:
          EARTHLY_SECRET_FILES: .envrc=.envrc
