name: CI

on:
  push:
    branches:
      - master

env:
  TZ: Asia/Hong_Kong

jobs:
  build:
    runs-on: ubuntu-latest
    container: hkssprangers/hkssprangers_devcontainer_workspace:20200808
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run postCreateCommand
        run: bash ./.devcontainer/postCreateCommand.sh
      - name: Compile index.js
        run: haxe build.hxml
      - name: Minify browser.js
        run: npx browserify browser.js -g [ envify --NODE_ENV production ] -g uglifyify | npx terser --compress --mangle > static/browser.bundled.js
      - name: Deploy
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          MYSQL_ENDPOINT: ${{ secrets.MYSQL_ENDPOINT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          TGBOT_TOKEN: ${{ secrets.TGBOT_TOKEN }}
      - name: Set tg bot webhook
        run: node index.js setTgWebhook
        env:
          TGBOT_TOKEN: ${{ secrets.TGBOT_TOKEN }}
