name: CI

on:
  push:
    branches:
      - master
      - production

env:
  TZ: Asia/Hong_Kong

jobs:
  build:
    runs-on: ubuntu-latest
    container: hkssprangers/hkssprangers_devcontainer_workspace:20201103
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/haxe
            node_modules
          key: ${{ runner.os }}
      - name: Run postCreateCommand
        run: bash ./.devcontainer/postCreateCommand.sh
      - name: Compile index.js
        run: haxe build.hxml
      - name: Minify browser.js
        run: npx browserify browser.js -g [ envify --NODE_ENV production ] -g uglifyify | npx terser --compress --mangle > static/browser.bundled.js
      - name: Test
        run: haxe test.hxml
      - name: Deploy master
        if: github.ref == 'refs/heads/master'
        run: |
          set -ex
          npx serverless deploy --stage master
          node index.js setTgWebhook https://master.ssprangers.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          FORM_READER_EMAIL: ${{ secrets.FORM_READER_EMAIL }}
          FORM_READER_PRIVATE_KEY: ${{ secrets.FORM_READER_PRIVATE_KEY }}
          TGBOT_TOKEN: ${{ secrets.TGBOT_TOKEN_MASTER }}
      - name: Deploy production
        if: github.ref == 'refs/heads/production'
        run: |
          set -ex
          npx serverless deploy --stage production
          node index.js setTgWebhook https://ssprangers.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          FORM_READER_EMAIL: ${{ secrets.FORM_READER_EMAIL }}
          FORM_READER_PRIVATE_KEY: ${{ secrets.FORM_READER_PRIVATE_KEY }}
          TGBOT_TOKEN: ${{ secrets.TGBOT_TOKEN_PRODUCTION }}
