name: CI
on: ["push", "pull_request"]

env:
  TZ: Asia/Hong_Kong
  FORCE_COLOR: 1
  EARTHLY_STRICT: "true"
  PUSH: "${{ github.repository_owner == 'hkssprangers' && github.event_name == 'push' }}"
  DEPLOY: "${{ github.repository_owner == 'hkssprangers' && github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/production' ) }}"

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        if: success() && env.PUSH == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Specify Earthly remote cache
        run: echo "EARTHLY_REMOTE_CACHE=ghcr.io/hkssprangers/hkssprangers_cache:$(echo "$GITHUB_REF_NAME" | sed 's/[^A-Za-z0-9\-\.]/_/g')" >> $GITHUB_ENV
      - name: Setup Earthly
        run: "sudo /bin/sh -c 'curl -fsSL https://github.com/earthly/earthly/releases/download/v0.6.10/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Build devcontainer
        run: earthly +ci-images --GIT_REF_NAME="${{ github.ref_name }}" --GIT_SHA="${{ github.sha }}"
        env:
          EARTHLY_PUSH: ${{ env.PUSH }}
      - name: Build
        run: earthly +server
      - name: Build importGoogleForm
        run: earthly +importGoogleForm-js
      - name: Test
        run: earthly +test
      - name: Create .envrc
        if: success() && env.DEPLOY == 'true'
        run: |
          cat > .envrc <<EOT
          export AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION"
          export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
          EOT
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      - name: Pre-deploy check
        if: success() && env.DEPLOY == 'true'
        run: earthly +pre-deploy-check --TF_LOCK_TIMEOUT=15m
        env:
          EARTHLY_SECRET_FILES: .envrc=.envrc
      - name: Create .envrc
        if: success() && env.DEPLOY == 'true'
        run: |
          tee .envrc <<EOT
          export AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION"
          export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
          export SERVERLESS_ACCESS_KEY="$SERVERLESS_ACCESS_KEY"
          export COCKROACH_HOST="$COCKROACH_HOST"
          export COCKROACH_PORT="$COCKROACH_PORT"
          export COCKROACH_USER="$COCKROACH_USER"
          export COCKROACH_PASSWORD="$COCKROACH_PASSWORD"
          export COCKROACH_DATABASE="$COCKROACH_DATABASE"
          export FORM_READER_EMAIL="$FORM_READER_EMAIL"
          export FORM_READER_PRIVATE_KEY="$FORM_READER_PRIVATE_KEY"
          export JWT_SECRET="$JWT_SECRET"
          export TWILIO_SID="$TWILIO_SID"
          export TWILIO_AUTH_TOKEN="$TWILIO_AUTH_TOKEN"
          EOT
          if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
            echo "DEPLOY_STAGE=master" >> $GITHUB_ENV
            echo "SERVER_HOST=master.ssprangers.com" >> $GITHUB_ENV
            echo "export TGBOT_TOKEN=${TGBOT_TOKEN_MASTER}" >> .envrc
          elif [ "${GITHUB_REF}" = "refs/heads/production" ]; then
            echo "DEPLOY_STAGE=production" >> $GITHUB_ENV
            echo "SERVER_HOST=ssprangers.com" >> $GITHUB_ENV
            echo "export TGBOT_TOKEN=${TGBOT_TOKEN_PRODUCTION}" >> .envrc
          fi
        env:
          AWS_DEFAULT_REGION: "ap-southeast-1"
          AWS_ACCESS_KEY_ID: "${{ secrets.SLS_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}"
          SERVERLESS_ACCESS_KEY: "${{ secrets.SERVERLESS_ACCESS_KEY }}"
          COCKROACH_HOST: "${{ secrets.COCKROACH_HOST }}"
          COCKROACH_PORT: "${{ secrets.COCKROACH_PORT }}"
          COCKROACH_USER: "${{ secrets.COCKROACH_USER }}"
          COCKROACH_PASSWORD: "${{ secrets.COCKROACH_PASSWORD }}"
          COCKROACH_DATABASE: "${{ secrets.COCKROACH_DATABASE }}"
          FORM_READER_EMAIL: "${{ secrets.FORM_READER_EMAIL }}"
          FORM_READER_PRIVATE_KEY: "${{ secrets.FORM_READER_PRIVATE_KEY }}"
          JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          TWILIO_SID: "${{ secrets.TWILIO_SID }}"
          TWILIO_AUTH_TOKEN: "${{ secrets.TWILIO_AUTH_TOKEN }}"
          TGBOT_TOKEN_MASTER: "${{ secrets.TGBOT_TOKEN_MASTER }}"
          TGBOT_TOKEN_PRODUCTION: "${{ secrets.TGBOT_TOKEN_PRODUCTION }}"
      - name: Deploy
        if: success() && env.DEPLOY == 'true'
        run: earthly +deploy --DEPLOY_STAGE="${DEPLOY_STAGE}" --SERVER_HOST="${SERVER_HOST}"
        env:
          EARTHLY_SECRET_FILES: .envrc=.envrc
      - name: Post-deploy tests
        if: success() && env.DEPLOY == 'true'
        run: earthly +post-deploy-test --SERVER_HOST="${SERVER_HOST}"
