name: DB-backup
on:
  schedule:
    # HKT 00:00
    - cron: '0 16 * * *'

env:
  TZ: Asia/Hong_Kong

jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hkssprangers/hkssprangers_devcontainer:master
    steps:
      - name: Backup
        shell: bash
        run: >-
          DATABASE_URL="postgresql://${COCKROACH_USER}:${COCKROACH_PASSWORD}@${COCKROACH_HOST}:${COCKROACH_PORT}/${COCKROACH_DATABASE#*.}?sslmode=require&options=--cluster%3d${COCKROACH_DATABASE%.*}";
          psql -d "$DATABASE_URL" -c "BACKUP INTO 's3://${S3_BUCKET}/${S3_PATH}?AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}&AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' AS OF SYSTEM TIME '-10s';"
        env:
          S3_BUCKET: hkssprangers-dbbackup
          S3_PATH: dbbackup
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          COCKROACH_HOST: "${{ secrets.COCKROACH_HOST }}"
          COCKROACH_PORT: "${{ secrets.COCKROACH_PORT }}"
          COCKROACH_USER: "${{ secrets.COCKROACH_USER }}"
          COCKROACH_PASSWORD: "${{ secrets.COCKROACH_PASSWORD }}"
          COCKROACH_DATABASE: "${{ secrets.COCKROACH_DATABASE }}"
