name: sendAttendancePoll

on:
  schedule:
    - cron: '0 2,9 * * *' # At 10:00 and 17:00 Hong Kong time

env:
  TZ: Asia/Hong_Kong

jobs:
  build:
    runs-on: ubuntu-latest
    container: hkssprangers/hkssprangers_devcontainer_workspace:20201103
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/haxe
            node_modules
          key: ${{ runner.os }}
      - name: Run postCreateCommand
        run: bash ./.devcontainer/postCreateCommand.sh
      - name: Compile and run
        run: haxe importGoogleForm.hxml && node importGoogleForm.js sendAttendancePoll
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          TGBOT_TOKEN: ${{ secrets.TGBOT_TOKEN_PRODUCTION }}
